FROM php:8.2-apache

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY . /var/www/html/

RUN sed -i 's/80/3000/g' /etc/apache2/ports.conf \
 && sed -i 's/:80/:3000/g' /etc/apache2/sites-available/000-default.conf

EXPOSE 3000